
steps:

- name: 'gcr.io/cloud-builders/git'
  id: 'src-prep'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -x
    rm -rf /workspace
    mkdir /workspace
    cd /workspace
    git clone $_REPO_URL .
    git fetch $_REPO_URL $COMMIT_SHA
    git checkout -b buildbranch FETCH_HEAD
    git branch --set-upstream-to=origin/$BRANCH_NAME buildbranch
    git config --global user.email "someone@example.com"
    git rebase

- name: 'gcr.io/kaniko-project/executor:latest'
  id: 'build'
  args:
  - --destination=us-docker.pkg.dev/$PROJECT_ID/servod/servod:$COMMIT_SHA
  - --cache=true
  - --cache-ttl=96h
  - -f=/workspace/servo/dockerfiles/Dockerfile.cq
  waitFor: ['src-prep']

- name: 'us-docker.pkg.dev/$PROJECT_ID/servod/servod:$COMMIT_SHA'
  id: 'test'
  entrypoint: pytest
  args:
    - -n=auto
    - --forked
    - --cov-report=html
    - --cov-report=xml
    - --cov-report=lcov
    - --cov=/usr/local/lib/python3.11/dist-packages/servo
    - --cov=/usr/local/lib/python3.11/dist-packages/usbkm232
    - --cov=/usr/local/lib/python3.11/dist-packages/ec3po
    - /hdctools/servo/tests/
  waitFor: ['build']

- name: 'python:slim'
  id: 'test-ec3po'
  entrypoint: 'bash'
  args:
    - /workspace/servo/ec3po/run_tests.sh
  waitFor: ['src-prep']

- name: 'pyfound/black:latest_release'
  id: 'test-black-formatting'
  entrypoint: 'black'
  args:
    - --check
    - --config=/workspace/pyproject.toml
    - /workspace
  waitFor: ['src-prep']

- name: 'xcgd/isort'
  id: 'test-isort-formatting'
  entrypoint: 'isort'
  args:
    - --check
    - /workspace
  waitFor: ['src-prep']

- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      set -ex

      cd /workspace
      gcloud config set project chromeos-hw-tools-dev
      # We overwrite htmlcov every CL - keep a copy as a history.
      cp -r htmlcov htmlcov.$COMMIT_SHA
      # Cloud storage serving requires absolute vs relative for src/href tags. Fix that.
      sed -i s#href=\"#href=\"https://storage.cloud.google.com/python-test-coverage/htmlcov/#g htmlcov/*
      sed -i s#src=\"#src=\"https://storage.cloud.google.com/python-test-coverage/htmlcov/#g htmlcov/*
      sed -i s#href=\"#href=\"https://storage.cloud.google.com/python-test-coverage/htmlcov.$COMMIT_SHA/#g htmlcov.$COMMIT_SHA/*
      sed -i s#src=\"#src=\"https://storage.cloud.google.com/python-test-coverage/htmlcov.$COMMIT_SHA/#g htmlcov.$COMMIT_SHA/*
      # Keep the coverage.xml - likely we can use this data to graph later.
      gsutil cp coverage.xml gs://python-test-coverage/coverage.$COMMIT_SHA.xml
      # Copy the test results to the cloud bucket
      gsutil -m cp -r htmlcov/ htmlcov.$COMMIT_SHA gs://python-test-coverage/
  waitFor: ['test']

options:
  machineType: 'N1_HIGHCPU_32'

timeout: 3600s
