# syntax=docker/dockerfile:1.4
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

######################################################################
FROM alpine/git as chromiumos_overlays
WORKDIR /
RUN git clone --filter=blob:none --no-checkout --depth 1 --sparse https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay
WORKDIR /chromiumos-overlay
RUN git sparse-checkout init --cone
RUN git sparse-checkout add dev-embedded/libftdi/files/ dev-embedded/libftdi/files/confs/
RUN git checkout

######################################################################
FROM debian:bookworm as clang-builder

RUN apt-get update \
    && apt-get install -y \
    autoconf \
    build-essential \
    clang \
    curl \
    git \
    libssl-dev \
    libtool \
    pkg-config \
    python3 \
    python3-distutils \
    python3-setuptools \
    python3-wheel \
    python3-grpc-tools \
    python3-grpcio \
    uuid-dev \
    wget
RUN update-alternatives --auto c++
RUN update-alternatives --auto cc

ENV CC=clang
ENV CXX=clang++
# Required to make the platform/ec makefile not think we are building
# from portage.
ENV BUILDCC_PREFIX=

######################################################################
FROM clang-builder as libusb-builder

RUN git clone https://github.com/libusb/libusb
WORKDIR /libusb
RUN git checkout "$(git tag -l | egrep '^v[0-9]+\.[0-9]+.[0-9]+$' | sort -V | tail -1)"

# Disable udev to avoid issues of libusb thinking the device is still attached
# after a software reboot.
RUN ./bootstrap.sh && ./configure --with-pic --disable-udev && make && make install

# Change the package config to have pthread for linking.
RUN sed -i 's/Libs: -L\${libdir} -lusb-1.0/Libs: -L\${libdir} -lusb-1.0 -lpthread /g' /libusb/libusb-1.0.pc

#####################################################################
FROM clang-builder as libftdi

RUN wget https://www.intra2net.com/en/developer/libftdi/download/libftdi1-1.2.tar.bz2 \
    && tar xf libftdi1-1.2.tar.bz2 \
    && rm libftdi1-1.2.tar.bz2

COPY --link --from=chromiumos_overlays \
    /chromiumos-overlay/dev-embedded/libftdi/files/libftdi-1.2-getopts.patch \
    /libftdi1-1.2/

COPY --link --from=chromiumos_overlays \
    /chromiumos-overlay/dev-embedded/libftdi/files/confs/*.conf \
    /usr/share/libftdi/

RUN apt-get update --no-install-recommends  \
    && apt-get install -y --no-install-recommends  \
    cmake \
    && rm -rf /var/lib/apt/lists/*


COPY --link --from=libusb-builder /usr/local/include/libusb-1.0/libusb.h /usr/local/include/libusb-1.0/
COPY --link --from=libusb-builder /usr/local/lib/libusb-1.0.a /usr/local/lib
COPY --link --from=libusb-builder /usr/local/lib/libusb-1.0.so.?.?.? /usr/local/lib/
COPY --link --from=libusb-builder /libusb/*.pc /usr/lib/pkgconfig/

WORKDIR /libftdi1-1.2

RUN git apply libftdi-1.2-getopts.patch

# The examples have a linking issue, not used for anything, disable them.
RUN sed -i s/.*examples.*//g CMakeLists.txt
RUN sed -i s/.*examples.*//g libftdi1.spec.in


RUN mkdir build \
    && cd build \
    && cmake -DCMAKE_INSTALL_PREFIX="/usr" ../ \
    && make \
    && make install

WORKDIR /

######################################################################
FROM libftdi as pigweed-builder

RUN git clone https://chromium.googlesource.com/external/pigweed/pigweed/pigweed

WORKDIR /pigweed
COPY servo/dockerfiles/setup_pigweed.py .
RUN python3 setup_pigweed.py bdist_wheel

######################################################################
FROM libftdi as hdctools-builder
COPY / hdctools/

RUN apt-get update \
    && apt-get install -y \
    protobuf-compiler \
    python3-pytest

WORKDIR /hdctools
RUN echo 'HOSTOS_CWARN=' >> 'defs/c-Linux.mk'
RUN make -j $(nproc)
RUN make install

# Setuptools skips nested entry point. Adding custom setup.py to overcome.
COPY /servo/dockerfiles/setup_hdctools.py .
RUN PACKAGE="servo" python3 setup_hdctools.py bdist_wheel
RUN PACKAGE="servo_updater" python3 setup_hdctools.py bdist_wheel

######################################################################
FROM hdctools-builder as hdctools-usbkm232-builder

RUN PACKAGE="usbkm232" python3 setup_hdctools.py bdist_wheel
######################################################################
FROM hdctools-builder as hdctools-servo_mfg-builder

RUN PACKAGE="servo_mfg" python3 setup_hdctools.py bdist_wheel
######################################################################
FROM hdctools-builder as hdctools-ec3po-builder

RUN PACKAGE="ec3po" python3 setup_hdctools.py bdist_wheel
######################################################################
FROM debian:bookworm-slim

# Install libusb.
COPY --link --from=libusb-builder /usr/local/include/libusb-1.0/libusb.h /usr/local/include/libusb-1.0/
COPY --link --from=libusb-builder /libusb/*.pc /usr/lib/pkgconfig/
COPY --link --from=libusb-builder /usr/local/lib/libusb-1.0.so.?.?.? /usr/local/lib/
COPY --link --from=libusb-builder /usr/local/lib/libusb-1.0.a /usr/local/lib

RUN apt-get update --no-install-recommends \
    && apt-get install -y --no-install-recommends \
    dnsutils \
    fwupd \
    iptables \
    iputils-ping \
    kmod \
    libatomic1 \
    libpci-dev \
    lsof \
    procps \
    sudo \
    usbutils \
    udev \
    xz-utils \
    build-essential \
    make \
    gcc \
    python3 \
    python3-mock \
    python3-numpy \
    python3-packaging \
    python3-pexpect \
    python3-protobuf \
    python3-serial \
    python3-pytest \
    python3-pytest-cov \
    python3-pytest-forked \
    python3-pytest-mock \
    python3-pytest-xdist \
    python3-usb \
    python3-requests \
    python3-pip \
    python3-grpc-tools \
    python3-grpcio \
    wget \
    && rm -rf /var/lib/apt/lists/* \
    && update-alternatives --set ip6tables /usr/sbin/ip6tables-nft


WORKDIR /hdctools/chromeos/
COPY --link --from=hdctools-builder /hdctools/chromeos/servod_utils.sh .
WORKDIR /wheels
COPY --link --from=hdctools-builder /hdctools/dist/* ./
COPY --link --from=hdctools-ec3po-builder /hdctools/dist/* ./
COPY --link --from=hdctools-usbkm232-builder /hdctools/dist/* ./
COPY --link --from=hdctools-servo_mfg-builder /hdctools/dist/* ./
COPY --link --from=pigweed-builder /pigweed/dist/*.whl ./
RUN pip3  install  *.whl --break-system-packages
WORKDIR /
RUN rm -rf wheels

RUN chmod u+x /usr/sbin/* /usr/bin/*

COPY --link --from=hdctools-builder /hdctools/servo/tests/ /hdctools/servo/tests/
COPY --link --from=hdctools-builder /hdctools/servo_mfg/tests/ /hdctools/servo_mfg/tests/
COPY --link --from=hdctools-builder /hdctools/ec3po/tests/ /hdctools/ec3po/tests/

ENV WARN_ONLY_ON_UNKNOWN_ENV="SERVO_FW_ALL_CHANNEL_OK"

COPY /servo/dockerfiles/start_servod.sh /servo/dockerfiles/stop_servod.sh \
    /

# Try to remove as much as possible to make the container smaller
RUN apt-get remove --purge -y \
    xz-utils \
    build-essential \
    make \
    gcc \
    python3-pip \
    wget \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /usr/local/lib/python*/site-packages/numpy/core/tests \
    && rm -rf /var/cache/debconf \
    && rm -rf /usr/share/doc \
    && rm -rf /usr/share/zoneinfo/
