# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

FROM alpine/curl as downloader

WORKDIR /usr/share/hub/
RUN curl --create-dirs -O --output-dir /usr/share/hub/ \
    https://fwupd.org/downloads/be2c9146ff4cfac5d647376c39ce0b78151e9f1a785a287e93ac3968aff2ed50-GenesysLogic_GL3590_64.17.cab

########################################################################
FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        fwupd
WORKDIR /usr/share/hub/
COPY --from=downloader /usr/share/hub/* /usr/share/hub/

CMD ["fwupdtool", "install", \
    "/usr/share/hub/e2c9146ff4cfac5d647376c39ce0b78151e9f1a785a287e93ac3968aff2ed50-GenesysLogic_GL3590_64.17.cab"]
