#!/usr/bin/env python3
# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Posts a comment to a Gerrit CL. Designed to be run from Cloud Build."""

import argparse
import json
import subprocess
import sys
import urllib.error
import urllib.request


try:
    import google.auth
    from google.auth import impersonated_credentials
    from google.auth.transport.requests import Request
except ImportError:
    print(
        "Missing required libraries. Please run: pip3 install google-auth requests",
        file=sys.stderr,
    )
    sys.exit(1)


def get_current_service_account():
    """Gets the current service account email from the GCP Metadata server."""
    try:
        req = urllib.request.Request(
            "http://metadata.google.internal/computeMetadata/v1"
            "/instance/service-accounts/default/email",
            headers={"Metadata-Flavor": "Google"},
        )
        with urllib.request.urlopen(req) as response:
            return response.read().decode("utf-8").strip()
    except Exception as e:
        print(f"Failed to get current service account email: {e}", file=sys.stderr)
        return None


def get_gerrit_scoped_token(service_account_email):
    """Gets an OAuth2 token explicitly scoped for Gerrit."""
    try:
        # Get the default Cloud Build credentials (cloud-platform scoped)
        default_creds, _project = google.auth.default()

        # Impersonate the same service account, but ask for the gerrit scope
        scoped_creds = impersonated_credentials.Credentials(
            source_credentials=default_creds,
            target_principal=service_account_email,
            target_scopes=["https://www.googleapis.com/auth/gerritcodereview"],
        )

        # Refresh to actually fetch the token from the GCP API
        scoped_creds.refresh(Request())
        return scoped_creds.token

    except Exception as e:
        print(f"Failed to get Gerrit-scoped token: {e}", file=sys.stderr)
        return None


def post_comment(gerrit_url, change_id, report_path, token):
    """Posts a comment to the specified Gerrit CL."""
    try:
        with open(report_path, "r", encoding="utf-8") as f:
            message = f.read()
    except FileNotFoundError:
        print(f"Report file not found: {report_path}", file=sys.stderr)
        sys.exit(1)

    # Use the triplet project~branch~changeId to be very specific if possible.
    # But for now, just ensure change_id is URL encoded if it's the I... format.
    # The Change-Id is already usually safe.
    url = f"{gerrit_url}/a/changes/{change_id}/revisions/current/review"
    print(f"Posting to Gerrit URL: {url}", file=sys.stderr)

    payload = {
        "message": message,
        "tag": "autogenerated:servo-xml-impact",
    }

    data = json.dumps(payload).encode("utf-8")

    req = urllib.request.Request(url, data=data, method="POST")
    req.add_header("Content-Type", "application/json")
    req.add_header("Authorization", f"Bearer {token}")

    try:
        with urllib.request.urlopen(req) as response:
            print(f"Successfully posted to Gerrit: {response.status}")
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8")
        print(
            f"Failed to post to Gerrit: {e.code} {e.reason}\nBody: {error_body}",
            file=sys.stderr,
        )
        sys.exit(1)
    except Exception as e:
        print(
            f"An unexpected error occurred while posting to Gerrit: {e}",
            file=sys.stderr,
        )
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description="Post a report to a Gerrit CL.")
    parser.add_argument("report_file", help="Path to the markdown report file.")
    parser.add_argument(
        "--gerrit-url",
        default="https://chromium-review.googlesource.com",
        help="Base URL of the Gerrit instance.",
    )
    parser.add_argument("--change-id", help="Gerrit Change-Id (e.g. I... or numeric).")
    parser.add_argument(
        "--service-account",
        help="The Cloud Build SA email. Fetched automatically if omitted.",
    )

    args = parser.parse_args()

    change_id = args.change_id
    if not change_id:
        # Get Change-Id directly from the most recent commit message
        try:
            log_output = subprocess.check_output(
                ["git", "log", "-1", "--format=%B"], text=True
            )
            for line in log_output.splitlines():
                if line.startswith("Change-Id:"):
                    change_id = line.split(":", 1)[1].strip()
                    break

            if not change_id:
                print(
                    "Could not find Change-Id in the commit message "
                    "and --change-id was not provided.",
                    file=sys.stderr,
                )
                sys.exit(1)

        except Exception as e:
            print(f"Error getting Change-Id from git: {e}", file=sys.stderr)
            sys.exit(1)

    print(f"Using Change-Id: {change_id}", file=sys.stderr)

    # Resolve service account identity
    service_account = args.service_account or get_current_service_account()
    if not service_account:
        print("Could not determine service account identity.", file=sys.stderr)
        sys.exit(1)

    print(f"Authenticating as: {service_account}", file=sys.stderr)

    auth_token = get_gerrit_scoped_token(service_account)
    if not auth_token:
        msg = "Could not obtain token. Are you running in Cloud Build?"
        print(msg, file=sys.stderr)
        sys.exit(1)

    post_comment(args.gerrit_url, change_id, args.report_file, auth_token)


if __name__ == "__main__":
    main()
