# Copyright 2013 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""Classes and objects for the Servo Client API."""

import http.client
import re
from xmlrpc.client import Fault
from xmlrpc.client import ServerProxy
from xmlrpc.client import Transport

from servo.common import defaults


DEFAULT_HOST = defaults.DEFAULT_HOST
DEFAULT_PORT = defaults.DEFAULT_PORT


class TimeoutTransport(Transport):
    """Custom XML-RPC transport to support timeouts."""

    def __init__(self, *args, timeout=None, **kwargs):
        self.timeout = timeout
        super().__init__(*args, **kwargs)

    def make_connection(self, host):
        if self._connection and host == self._connection[0]:
            return self._connection[1]
        chost, self._extra_headers, _x509 = self.get_host_info(host)
        self._connection = host, http.client.HTTPConnection(chost, timeout=self.timeout)
        return self._connection[1]


class ServoClientError(Exception):
    """Error class for ServoRequest"""

    def __init__(self, text, xmlexc):
        """Constructor for ServoClientError Class

        This class wraps Fault exceptions.

        Args:
          text: a string, error message generated by caller of exception handler
          xmlexc: Fault object supplied by the caught exception. In some
                  cases is replaced with None and ignored.

        Fault.faultString has the following format:

        <type 'exception type'>:'actual error message'

        we filter out the actual error message to make it available for the
        downstream exception handler
        """
        if xmlexc:
            xml_error = re.sub(r"^.*>:", "", xmlexc.faultString).strip()
            message = f"{text} :: {xml_error}"
        else:
            message = text
        super().__init__(message)


class ServoClient:
    """Class to link client to servod via xmlrpc.

    Beyond method initialize, the remaining methods (doc_all, doc, get, get_all,
    set) have a corresponding method implemented in servod's server.
    """

    def __init__(
        self, host=DEFAULT_HOST, port=DEFAULT_PORT, verbose=False, timeout=60.0
    ):
        """Constructor for ServoClient Class

        Args:
          host: name or IP address of servo server host
          port: TCP port on which servod is listening on
          verbose: enable verbose messaging across ServerProxy
          timeout: timeout in seconds for XML-RPC requests
        """
        self._verbose = verbose
        self._timeout = timeout
        remote = "http://%s:%s" % (host, port)
        transport = TimeoutTransport(timeout=self._timeout)
        self._server = ServerProxy(
            remote, transport=transport, verbose=self._verbose, allow_none=True
        )

    def doc_all(self):
        """Get the doc string for all controls from servo.

        Returns:
         string of all doc strings of controls from servo.
        """
        return self._server.doc_all()

    def doc(self, name):
        """Get the doc string from servo for control name.

        Args:
          name: string, name of control to retrieve doc string for.

        Returns:
         doc string for control name

        Raises:
          ServoClientError: If error occurs retrieving doc string.
        """
        try:
            return self._server.doc(name)
        except Fault as e:
            raise ServoClientError("Problem docstring '%s'" % name, e) from e

    def get(self, name):
        """Get the value from servo for control name.

        Args:
          name: string, name of control to get value for.

        Returns:
         value currently set on control name

        Raises:
          ServoClientError: If error occurs getting value.
        """
        try:
            return self._server.get(name)
        except Fault as e:
            raise ServoClientError("Problem getting '%s'" % name, e) from e

    def get_all(self):
        """Get all controls current values.

        Returns:
          String of all controls and their current values
        """
        return self._server.get_all(self._verbose)

    def set_get_all(self, controls):
        """Set &| get one or more control values.

        Args:
          controls: string, controls to set &| get.

        Raises:
          ServoClientError: If error occurs setting value.
        """
        try:
            rv = self._server.set_get_all(controls)
        except Fault as e:
            # TODO(tbroch) : more detail of failure.  Note xmlrpclib only
            #                passes one exception above
            raise ServoClientError("Problem with %s" % (controls), e) from e
        return rv

    def set(self, name, value):
        """Set the value from servo for control name.

        Args:
          name: string, name of control to set.
          value: string, value to set control to.

        Raises:
          ServoClientError: If error occurs setting value.
        """
        try:
            self._server.set(name, value)
        except Fault as e:
            # TODO(tbroch) : more detail of failure.  Note xmlrpclib only
            #                passes one exception above
            raise ServoClientError(
                "Problem setting '%s' to '%s'" % (name, value), e
            ) from e

    def ftdii2c(self, args):
        """Calling a method of Fi2c."""
        self._server.ftdii2c(args)

    def hwinit(self):
        """Initialize the controls."""
        self._server.hwinit()
