
// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/wrappers.proto";

/*
    The DriverService provides RPC methods for interacting with drivers and interfaces.
 */
service DriverService {
    // CallDriver is used to get or set values through the driver.
    // It takes a DriverRequest and returns a DriverResponse.
    rpc CallDriver (DriverRequest) returns (DriverResponse);
    // InitInterface is used to initialize interfaces for servo devices.
    // It takes an InterfaceRequest and returns an InterfaceResponse.
    rpc InitInterface(InterfaceRequest) returns (InterfaceResponse);
    // ReinitializeInterfaces is used to reinitialize interfaces for servo devices.
    rpc ReinitializeInterfaces(InterfaceRequest) returns (google.protobuf.Empty);
    // CloseInterface is used to close specified interface.
    rpc CloseInterface(InterfaceRequest) returns (google.protobuf.Empty);
    // Set log level for interfaces in interface_list
    rpc SetInterfacesLoglevel(LogRequest) returns (google.protobuf.Empty);
    // sync interface list
    rpc SyncInterfaceList(InterfaceRequest) returns (google.protobuf.Empty);
    // Set ftdii2c cmd
    rpc SetFtdii2cCmd(Ftdii2cCmdRequest) returns (google.protobuf.Empty);
    // reset init interface
    rpc ResetInterface(ResetInterfaceRequest) returns (google.protobuf.Empty);
    // Limit EC channels to console commands only
    rpc LimitEcDriverChannel(EcChannelRequest) returns (google.protobuf.Empty);
    // Restore EC channels
    rpc RestoreEcDriverChannel(EcChannelRequest) returns (google.protobuf.Empty);
    // Issue command in EC console.
    rpc IssueCmdGetResults(IssueCmdRequest) returns (google.protobuf.Empty);
    // Check if device exists
    rpc CheckDevice(DeviceRequest) returns (google.protobuf.BoolValue);
}

message DeviceRequest {
    // Sysfs path of the device
    string sysfs_path = 1;
}

message EcChannelRequest
{
    // PID
    int32 pid = 1;
    // VID
    int32 vid = 2;
    // Serial
    string serial = 3;
    // Device type
    string device_type = 4;
    // Control that uses requested driver
    string control_name = 5;
}

message DriverRequest {
    // Default interface template
    string interface_template = 1;
    // PID
    int32 pid = 2;
    // VID
    int32 vid = 3;
    // Serial
    string serial = 4;
    // Device type
    string device_type = 5;
    // control name that need to be set/get on the driver
    string control_name = 6;
    // the value the need to be set on the driver
    // For get, it sent empty
     oneof set_value {
         // set value
        google.protobuf.Value value = 7;
        google.protobuf.Empty set_empty_value = 8;
    }
}

message DriverResponse {
    // Return driver get/set result
    bool success = 3;
    oneof response {
        string value = 1;
        google.protobuf.Empty empty_value = 2;
    }
}

message InterfaceRequest {
    // vid
    int32 vid = 1;
    // pid
    int32 pid = 2;
    // serial
    string serial = 3;
    // interface default template
    string interface_template = 4;

    bool fault_tolerant = 5;
    // Path to tokens database
    string token_db = 6;
}

message InterfaceResponse {
    // init interface response
    bool success = 1;
    // Log lines captured during the initialization
    repeated string loglines = 2;
}

message LogRequest {
    string name = 1;
}

message Ftdii2cCmdRequest {
    string cmd = 1;
}

message ResetInterfaceRequest {
    // vid
    int32 vid = 1;
    // pid
    int32 pid = 2;
    // serial
    string serial = 3;
    // interface index
    int32 interface_index = 4;
}

message IssueCmdRequest {
    // PID
    int32 pid = 1;
    // VID
    int32 vid = 2;
    // Serial
    string serial = 3;
    // Device type
    string device_type = 4;
    // Commands
    string cmds = 5;
    // Regexes
    repeated string regex_list = 6;
    // Do flush
    bool flush = 7;
    // Command timeout
    int32 time_out = 8;
}
