# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

FROM us-docker.pkg.dev/chromeos-hw-tools/servod/dev_env:latest

ARG USER
ARG USERID

RUN adduser --gecos "" --disabled-password --uid ${USERID} ${USER}
RUN echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER $USER
