#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:           local-docker-proxy
# Required-Start:     docker
# Required-Stop:      docker
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  Create lightweight, portable, self-sufficient containers.
# Description: Docker dns proxy that allows containers to be addressed by name from chroot.
### END INIT INFO


. /lib/lsb/init-functions

# Carry out specific functions when asked to by the system
case "$1" in
    start)
        echo "Starting script local "
	/usr/bin/docker stop docker-proxy || true
	/usr/bin/docker pull defreitas/dns-proxy-server
	/usr/bin/docker rm docker-proxy || true
        /usr/bin/docker run -d --name docker-proxy --hostname dns.mageddo --restart=unless-stopped -p 5380:5380 -v /var/run/docker.sock:/var/run/docker.sock -v /etc/resolv.conf:/etc/resolv.conf defreitas/dns-proxy-server
    ;;
    stop)
        echo "Stopping script local-docker-proxy"
        /usr/bin/docker stop docker-proxy
    ;;
    e)
        echo "Usage: /etc/init.d/local-docker-proxy {start|stop}"
        exit 1
    ;;
esac

exit 0
