# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
events {}

http {
    server {
        listen 80;
        location / {
            root /file_cache;
            sendfile on;
        }

    }
}


