# Copyright 2022 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""Servo Device Templates."""

import collections
import inspect
import logging
import re
import sys

# Main devices have an empty prefix. This constant here is to make those checks
# uniform.
MAIN_DEV_PREFIX = 'main'

# This alias is used for the main device on servo_server (the device without a
# prefix) to allow for precise routing and server controls that need to indicate
# which device they want things to happen on.
MAIN_DEV_PREFIX_ALIAS = ''

# SERVO_VID_PID_TEMPLATE_MAP, SERVO_LOTID_TEMPLATE_MAP and SERVO_ID_DEFAULTS gets
# populated on module import to keep a single source of truth about the device
# information - their template classes.
# A 2d map to fetch a servo device template given a vendor id and a product id.
SERVO_VID_PID_TEMPLATE_MAP = collections.defaultdict(lambda: collections.defaultdict(set))
# A dict to fetch a servo device template given a lot id.
SERVO_LOTID_TEMPLATE_MAP = collections.defaultdict(set)
# A set of tuples of the vid/pid pairs of all known servo devices.
SERVO_ID_DEFAULTS = set()

# Lot IDs are used to distinguish between servo v2 and servo v2 r0. If a device
# has a lot-id that is not known, it gets assigned a fake lot id to ensure that
# it registers as v2 as after a while all the new(er) lotids are v2.
FORCE_V2_LOTID = 'force-v2-lotid'

class DeviceTemplateError(Exception):
  """Error class for device templates."""
  pass

def GetTemplateClass(vid, pid, serial=None):
  """Get the ServoDevTemplate class associated with (vid, pid, serial).

  Note: the serialname is only used when (vid, pid) leave ambiguity (more than
  one template class) and the serialname is needed to determine the lot-id

  Args:
    vid: vendor id for a servo device
    pid: product id for a servo device
    serial: serialname of servo device in question

  Returns:
    servo dev template class associated with (vid, pid, serial)

  Raises:
    DeviceTemplateError if template class not found, or not uniquely identified
  """
  dev_class_candidates = SERVO_VID_PID_TEMPLATE_MAP[vid][pid].copy()
  if len(dev_class_candidates) > 1:
    # Might need the lotid to distinguish what device is used.
    if serial:
      try:
        lotid, _ = serial.split('-')
        logging.info('Retrieved lot-id %r for sid: %r.', lotid, serial)
      except ValueError:
        logging.debug('Could not retrieve lot-id for sid: %r.', serial)
        lotid = ''
      if lotid not in SERVO_LOTID_TEMPLATE_MAP:
        # This usually means that it's a servo-v2 and not servo-v2-r0, so
        # assign a fake lot-id to force servo-v2.
        logging.info('Lotid %r not in lotid map. Assigning fake lot id '
                     'to force servo v2 selection.', lotid)
        lotid = FORCE_V2_LOTID
      dev_class_candidates &= SERVO_LOTID_TEMPLATE_MAP[lotid]
  dev_str = '[%04x:%04x%s]' % (vid, pid, ' ' + serial if serial else '')
  if not dev_class_candidates:
    logging.error('Could not find a ServoDev class for %s.', dev_str)
    return None
  if len(dev_class_candidates) > 1:
    logging.error('Multiple ServoDev template classes found for %s. This '
                  'should not happen.', dev_str)
    for dev_class in dev_class_candidates:
      logging.error('Found ServoDev template class %s', dev_class.__name__)
    return None
  return dev_class_candidates.pop()

def _CamelToSnakeCase(iput):
  """Convert CamelCase to snake_case, and remove trailing underscores.
  Substitute each upper-case letter preceded by a lower-case one (or number)
  with a _ and its lower case equivalent.
  Args:
    iput: input string to convert
  Returns:
    iput string converted to camel-case
  """
  s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', iput)
  return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).rstrip('_').lower()

class _ServoDevTemplate(object):
  """Base servo device template class.
  Servo device template classes are classes to centrally collect information
  about a servo device. This us to quickly answer questions about different
  servo devices, and to abstract capabilities from device types/names by
  having different capabilities just be attributes.
  """

  # The Vendor ID associated with this servo device
  VID = None
  # The product ID associated with this servo device
  PID = None
  # A tuple of (VID, PID). This is autogenerated.
  ID = None
  # For some servo devies, different lot ids (from serialname) identify the
  # template class
  LOTIDS = None
  # The default configuration file to pull in for this servo device
  DEFAULT_CONFIG = None
  # The type string of a servo device
  TYPE = 'unknown'
  # The ServoDev class used for the servo device
  DEV_CONSTRUCTOR = None

class MiniservoV1(_ServoDevTemplate):
  """Mini-servo template class."""
  TYPE = 'miniservo_v1'
  VID = 0x18d1
  PID = 0x5000
  LOTIDS = ['001', '540052']
  DEFAULT_CONFIG = 'miniservo.xml'

class ServoV1(_ServoDevTemplate):
  """Servo v1 template class."""
  TYPE = 'servo_v1'
  VID = 0x18d1
  PID = 0x5001
  LOTIDS = ['483881', '498432']
  DEFAULT_CONFIG = 'servo.xml'

class ServoV2R0(_ServoDevTemplate):
  """Servo v2 r0 template class."""
  TYPE = 'servo_v2_r0'
  VID = 0x18d1
  PID = 0x5002
  LOTIDS = ['609600', '629871']
  DEFAULT_CONFIG = 'servo_v2_r0.xml'

class ServoV2(ServoV2R0):
  """Servo v2 template class."""
  TYPE = 'servo_v2'
  LOTIDS = ['641200', '686203', '730422', '780735', '868534', '875286',
            FORCE_V2_LOTID]
  DEFAULT_CONFIG = 'servo_v2_r1.xml'

class ServoV3(_ServoDevTemplate):
  """Servo v3 template class."""
  TYPE = 'servo_v3'
  VID = 0x18d1
  PID = 0x5004
  DEFAULT_CONFIG = 'servo_v3_r0.xml'

class ServoV3_(ServoV3):
  """Servo v2 template class for misprogrammed v3s.
  The background here is that some servo v3's did not properly have their
  vid/pid set to Google/Servo V3, but rather are still FTDI/ft232h
  """
  # pylint: disable=invalid-name
  # See docstring
  VID = 0x0403
  PID = 0x6014

class ServoV4(_ServoDevTemplate):
  """Servo v4 template class."""
  TYPE = 'servo_v4'
  VID = 0x18d1
  PID = 0x501b
  DEFAULT_CONFIG = 'servo_v4.xml'

class ServoV4p1(_ServoDevTemplate):
  """Servo v4p1 template class."""
  TYPE = 'servo_v4p1'
  VID = 0x18d1
  PID = 0x520d
  DEFAULT_CONFIG = 'servo_v4p1.xml'

class ServoMicro(_ServoDevTemplate):
  """Servo micro template class."""
  TYPE = 'servo_micro'
  VID = 0x18d1
  PID = 0x501a
  DEFAULT_CONFIG = 'servo_micro.xml'

class CcdCr50(_ServoDevTemplate):
  """Servo ccd cr50 template class."""
  TYPE = 'ccd_cr50'
  VID = 0x18d1
  PID = 0x5014
  DEFAULT_CONFIG = 'ccd_cr50.xml'

class CcdTi50(_ServoDevTemplate):
  """Servo ccd cr50 template class."""
  TYPE = 'ccd_ti50'
  VID = 0x18d1
  PID = 0x504a
  DEFAULT_CONFIG = 'ccd_ti50.xml'

class Sweetberry(_ServoDevTemplate):
  """Sweetberry template class."""
  TYPE = 'sweetberry'
  VID = 0x18d1
  PID = 0x5020
  DEFAULT_CONFIG = 'sweetberry.xml'

class C2d2(_ServoDevTemplate):
  """C2D2 template class."""
  TYPE = 'c2d2'
  VID = 0x18d1
  PID = 0x5041
  DEFAULT_CONFIG = 'c2d2.xml'

class ToadV1(_ServoDevTemplate):
  """Toad template class."""
  TYPE = 'toad_v1'
  VID = 0x0403  # Vendor ID is 0x0403 : FTDI
  PID = 0x6015
  DEFAULT_CONFIG = 'toad.xml'

class Reston(_ServoDevTemplate):
  """Reston template class."""
  TYPE = 'reston'
  VID = 0x18d1
  PID = 0x5007
  DEFAULT_CONFIG = 'reston.xml'

class Fruitpie(_ServoDevTemplate):
  """Fruitpie template class."""
  TYPE = 'fruitpie'
  VID = 0x18d1
  PID = 0x5009
  DEFAULT_CONFIG = 'fruitpie.xml'

class Plankton(_ServoDevTemplate):
  """Plankton template class."""
  TYPE = 'plankton'
  VID = 0x18d1
  PID = 0x500c
  DEFAULT_CONFIG = 'plankton.xml'

class Fluffy(_ServoDevTemplate):
  """Fluffy template class."""
  TYPE = 'fluffy'
  VID = 0x18d1
  PID = 0x503b
  DEFAULT_CONFIG = 'fluffy.xml'

def _InitMaps(servo_dev_module):
  """Helper to initialize the vid/pid/lotid maps for easy retrieval.
  This helper gets called on module import to populate the vid/pid/lotid
  maps with the right classes, to facilitate retrieval of the template class.
  It also calls GenerateType on each class to ensure that the type string
  is properly setup.
  Args:
    servo_dev_module: a reference to this very module
  """
  classes = inspect.getmembers(servo_dev_module, inspect.isclass)
  for cname, c in classes:
    if cname.endswith('Error'):
      continue
    if c.VID and c.PID:
      # This means the class refers to a physical servo device class.
      # Generate the servo device ID - (vid, pid)
      c.ID = (c.VID, c.PID)
      # Populate the SERVO_ID_DEFAULTS set
      SERVO_ID_DEFAULTS.add(c.ID)
      # Populate the lookup maps to allow for retrieval.
      SERVO_VID_PID_TEMPLATE_MAP[c.VID][c.PID].add(c)
      if c.LOTIDS:
        for lotid in c.LOTIDS:
          SERVO_LOTID_TEMPLATE_MAP[lotid].add(c)
# on import, run initialization
_InitMaps(sys.modules[__name__])
# Collection of secondary servos that usually require a support device (v4 or v4p1) to
# offer full servo functionality.
SECONDARY_SERVOS = set([ServoMicro.ID, CcdCr50.ID, CcdTi50.ID, C2d2.ID])