# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

steps:

- name: 'gcr.io/cloud-builders/git'
  id: 'src-prep'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -x
    rm -rf /workspace
    mkdir /workspace
    cd /workspace
    git clone $_REPO_URL .
    git fetch $_REPO_URL $COMMIT_SHA
    git checkout -b buildbranch FETCH_HEAD
    git branch --set-upstream-to=origin/$BRANCH_NAME buildbranch
    git config --global user.email "someone@example.com"
    git rebase

- name: 'gcr.io/kaniko-project/executor:latest'
  id: 'build'
  args:
  - --destination=us-docker.pkg.dev/$PROJECT_ID/servod/servod:$COMMIT_SHA
  - --cache=true
  - --cache-ttl=24h
  - --build-arg=BUILDER_BASE_IMG=us-docker.pkg.dev/$PROJECT_ID/servod/servod-builder-base:latest
  - --build-arg=BASE_IMG=us-docker.pkg.dev/$PROJECT_ID/servod/servod-base:latest
  - -f=/workspace/dockerfiles/Dockerfile
  waitFor: ['src-prep']

- name: 'gcr.io/kaniko-project/executor:latest'
  id: 'test-build'
  args:
  - --destination=us-docker.pkg.dev/$PROJECT_ID/servod/servodtest:$COMMIT_SHA
  - --cache=true
  - --cache-ttl=24h
  - --build-arg=BASE_IMG=us-docker.pkg.dev/$PROJECT_ID/servod/servod:$COMMIT_SHA
  - -f=/workspace/dockerfiles/Dockerfile.test
  waitFor: ['build']

- name: 'us-docker.pkg.dev/$PROJECT_ID/servod/servodtest:$COMMIT_SHA'
  id: 'test-python'
  entrypoint: pytest
  env:
    - PYTHONPATH=/workspace/
    - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
  args:
    - -n=logical
    - --cov-report=lcov
    - --cov-report=xml
    - --forked
    - --cov=/usr/local/lib/python3.13/dist-packages/servo
    - --cov=/usr/local/lib/python3.13/dist-packages/usbkm232
    - --cov=/usr/local/lib/python3.13/dist-packages/ec3po
    - /workspace/
  waitFor: ['test-build']


- name: 'pyfound/black:25.9.0'
  id: 'test-black-formatting'
  entrypoint: 'black'
  args:
    - --check
    - --config=/workspace/pyproject.toml
    - /workspace
  waitFor: ['src-prep']

- name: 'xcgd/isort'
  id: 'test-isort-formatting'
  entrypoint: 'isort'
  args:
    - --check
    - /workspace
  waitFor: ['src-prep']

- name: 'registry.gitlab.com/pipeline-components/pylint:latest'
  id: 'test-pylint'
  entrypoint: 'pylint'
  args:
    - --rcfile=/workspace/pylintrc
    - /workspace
  waitFor: ['src-prep']

- name: 'koalaman/shellcheck-alpine'
  id: 'test-shellcheck'
  waitFor: ['src-prep']
  entrypoint: 'sh'
  args:
  - '-c'
  - find /workspace -type f  -name *.sh -print | xargs shellcheck

- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  id: 'test-scripts'
  args:
    - -c
    - |
      set -e
      for script in $(ls /workspace/servo/tests/shell/*); do
         bash ${script}
      done
  waitFor: ['src-prep']


- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  id: 'coverage-upload-python'
  args:
    - -c
    - |
      set -ex

      cd /workspace
      gcloud config set project chromeos-hw-tools-dev
      # Copy to ng3 metrics
      # The parser is picky, so drop lines that are of no use to it
      sed -e "/^BRDA:0,/ d" coverage.lcov > coverage.edited.lcov
      gsutil cp coverage.edited.lcov gs://ng3-metrics/ng3-hw-tools-coverage/absolute/hdctools/$COMMIT_SHA/coverage.out
      cat > metadata.json << EOF
      {
        "host": "chromium",
        "project": "chromiumos/codesearch",
        "trace_type": "LCOV",
        "trim_prefix": "/usr/local/lib/python3.13/dist-packages/",
        "add_prefix": "src/third_party/hdctools/",
        "commit_id": "${COMMIT_SHA}",
        "ref": "refs/heads/main",
        "source": "zoss-uploader-hw-tools:main",
        "owner": "1192509288844",
        "bug_component": "983411"
      }
      EOF
      gsutil cp metadata.json gs://ng3-metrics/ng3-hw-tools-coverage/absolute/hdctools/$COMMIT_SHA/metadata.json
  waitFor: ['test-python']

options:
  pool:
    name: 'projects/chromeos-hw-tools-dev/locations/us-central1/workerPools/proto-servo-pool'

timeout: 5400s
