# syntax=docker/dockerfile:1.4
# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

######################################################################
FROM alpine/git as chromiumos_overlays
WORKDIR /
RUN git clone --filter=blob:none --no-checkout --depth 1 --sparse https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay
WORKDIR /chromiumos-overlay
RUN git sparse-checkout init --cone
RUN git sparse-checkout add dev-embedded/libftdi/files/ dev-embedded/libftdi/files/confs/
RUN git checkout

######################################################################
FROM alpine/git as shflags-builder

WORKDIR /
RUN git clone https://github.com/kward/shflags.git
WORKDIR /shflags
RUN git checkout "$(git tag -l | egrep '^v[0-9]+\.[0-9]+.[0-9]+$' | sort -V | tail -1)"

#####################################################################

FROM debian:trixie as clang-builder

RUN apt-get update \
    && apt-get install -y \
    autoconf \
    build-essential \
    equivs \
    clang \
    curl \
    git \
    libssl-dev \
    libtool \
    pkg-config \
    python3 \
    python3-setuptools \
    python3-wheel \
    python3-grpc-tools \
    python3-grpcio \
    uuid-dev \
    wget
RUN update-alternatives --auto c++
RUN update-alternatives --auto cc

ENV CC=clang
ENV CXX=clang++
# Required to make the platform/ec makefile not think we are building
# from portage.
ENV BUILDCC_PREFIX=

# Override the libraries we build ourselves, and do it early: no need to mess
# up the library builds by building against distro packages that we don't
# intend to use.
COPY dockerfiles/equivs-control .
RUN equivs-build equivs-control
RUN apt-get install -y ./hdctools-docker-fake_9999-1_all.deb

######################################################################
FROM clang-builder as libusb-builder

RUN git clone https://github.com/libusb/libusb
WORKDIR /libusb
RUN git checkout "$(git tag -l | egrep '^v[0-9]+\.[0-9]+.[0-9]+$' | sort -V | tail -1)"

# Disable udev to avoid issues of libusb thinking the device is still attached
# after a software reboot.
RUN ./bootstrap.sh && ./configure --with-pic --disable-udev && make -j$(nproc) && make install

# Change the package config to have pthread for linking.
RUN sed -i 's/Libs: -L\${libdir} -lusb-1.0/Libs: -L\${libdir} -lusb-1.0 -lpthread /g' /libusb/libusb-1.0.pc

RUN echo "libusb $(git rev-parse HEAD)" >> /version.txt

#####################################################################
FROM clang-builder as libftdi

RUN wget https://www.intra2net.com/en/developer/libftdi/download/libftdi1-1.5.tar.bz2 \
    && tar xf libftdi1-1.5.tar.bz2 \
    && rm libftdi1-1.5.tar.bz2


COPY --from=chromiumos_overlays \
    /chromiumos-overlay/dev-embedded/libftdi/files/confs/*.conf \
    /usr/share/libftdi/

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    cmake \
    libconfuse-dev \
    && rm -rf /var/lib/apt/lists/*


COPY --from=libusb-builder /usr/local/include/libusb-1.0/libusb.h /usr/local/include/libusb-1.0/
COPY --from=libusb-builder /usr/local/lib/libusb-1.0.a /usr/local/lib
COPY --from=libusb-builder /usr/local/lib/libusb-1.0.so.?.?.? /usr/local/lib/
COPY --from=libusb-builder /libusb/*.pc /usr/lib/pkgconfig/

WORKDIR /libftdi1-1.5

RUN mkdir build \
    && cd build \
    && cmake -DCMAKE_INSTALL_PREFIX="/usr" ../ \
    && make -j$(nproc) \
    && make install

WORKDIR /

######################################################################
FROM libftdi as ec-builder

RUN git clone https://chromium.googlesource.com/chromiumos/platform/ec

WORKDIR /

RUN git clone https://chromium.googlesource.com/chromiumos/third_party/flashmap

WORKDIR /flashmap
RUN make && make install
RUN echo "flashmap $(git rev-parse HEAD)" >> /version.txt

# Install libusb.
COPY --from=libusb-builder /usr/local/include/libusb-1.0/libusb.h /usr/local/include/libusb-1.0/
COPY --from=libusb-builder /usr/local/lib/libusb-1.0.a /usr/local/lib
COPY --from=libusb-builder /usr/local/lib/libusb-1.0.so.?.?.? /usr/local/lib/
COPY --from=libusb-builder /libusb/libusb-1.0.pc /usr/local/pkg/
ENV PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/usr/local/pkg/

WORKDIR /ec
#RUN find . -type f -name "Makefile*" -exec sed -i 's#-Werror # #'  {} \;
RUN make build/host/util/iteflash BOARD=host && \
    make build/host/util/itecomdbgr BOARD=host && \
    make build/host/util/uartupdatetool BOARD=host&& \
    make build/host/util/stm32mon BOARD=host && \
    make build/host/util/rtkupdate BOARD=host && \
    make -C extra/usb_updater usb_updater2

COPY servo/dockerfiles/setup_ec.py .
RUN PACKAGE="powerlog" python3 setup_ec.py bdist_wheel
RUN PACKAGE="console" python3 setup_ec.py bdist_wheel
RUN PACKAGE="unpack_ftb" python3 setup_ec.py bdist_wheel

RUN strip /ec/extra/usb_updater/usb_updater2 \
    /ec/build/host/util/stm32mon \
    /ec/build/host/util/uartupdatetool \
    /ec/build/host/util/iteflash \
    /ec/build/host/util/itecomdbgr \
    /ec/build/host/util/rtkupdate

RUN strip --strip-unneeded /usr/lib/libfmap.so* /usr/lib/libftdi*
RUN echo "ec $(git rev-parse HEAD)" >> /version.txt

WORKDIR /
RUN tar cvf libs.tar /usr/lib/libfmap.so* /usr/lib/libftdi*

######################################################################
FROM libftdi as pigweed-builder
ARG PIGWEED_URL=https://chromium.googlesource.com/chromiumos/third_party/pigweed/pigweed
ARG PIGWEED_BRANCH=main

RUN git clone ${PIGWEED_URL}

WORKDIR /pigweed
RUN git fetch ${PIGWEED_URL} ${PIGWEED_BRANCH}
RUN git checkout ${PIGWEED_BRANCH}
COPY dockerfiles/setup_pigweed.py .
RUN python3 setup_pigweed.py bdist_wheel

RUN echo "pigweed $(git rev-parse HEAD)" >> /version.txt

######################################################################
FROM libftdi as gcstool-builder

RUN git clone --depth 1 https://chromium.googlesource.com/chromiumos/platform/ec

WORKDIR /ec

RUN git fetch origin gsc_utils --depth 1 && git checkout FETCH_HEAD
RUN find . -type f -name "Makefile*" -exec sed -i 's#-Werror # #'  {} \;
RUN make -j$(nproc) -C extra/usb_updater gsctool

RUN strip  /ec/extra/usb_updater/gsctool

######################################################################
FROM libftdi as hdctools-builder-base

COPY dockerfiles/requirements_base.txt /tmp/requirements_base.txt

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    python3-pip \
    python3-packaging \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install --require-hashes --ignore-installed -r /tmp/requirements_base.txt --break-system-packages

######################################################################
FROM libftdi as flashrom-builder

WORKDIR /

RUN apt-get update \
    && apt-get install -y \
    meson \
    ninja-build \
    cmake \
    libcmocka-dev \
    libpci-dev

RUN git clone https://chromium.googlesource.com/chromiumos/third_party/flashrom

WORKDIR /flashrom
RUN meson builddir && cd builddir && meson install
RUN strip /usr/local/sbin/flashrom
RUN echo "flashrom $(git rev-parse HEAD)" >> /version.txt

######################################################################
FROM flashrom-builder as futility-builder

RUN apt-get update \
    && apt-get install -y \
    libnss3-dev

# Install vboot.
WORKDIR /
RUN git clone https://chromium.googlesource.com/chromiumos/platform/vboot_reference
WORKDIR /vboot_reference
RUN sed -i 's/%" PRIi64 "/%ld/g' futility/cmd_gbb_utility.c
RUN sed -i 's/-Werror//g' Makefile
RUN make && make install

RUN strip /usr/bin/futility
RUN echo "futility $(git rev-parse HEAD)" >> /version.txt

######################################################################
FROM futility-builder as coreboot

WORKDIR /
RUN git clone --depth 1 https://chromium.googlesource.com/chromiumos/third_party/coreboot
RUN cd /coreboot/util/cbfstool && make VBOOT_SOURCE=/vboot_reference
RUN strip /coreboot/util/cbfstool/cbfstool
RUN cd /coreboot/util/ifdtool && make
RUN strip /coreboot/util/ifdtool/ifdtool

WORKDIR /coreboot
RUN echo "coreboot $(git rev-parse HEAD)" >> /version.txt

######################################################################
FROM libftdi as fwupd-builder

RUN apt update
RUN apt install -y xz-utils wget build-essential dh-make devscripts meson ninja-build libglib2.0-dev libxmlb-dev libjcat-dev libzstd-dev libcurl4-gnutls-dev libarchive-dev libsqlite3-dev libgpgme-dev libgudev-1.0-dev usbutils python3-jinja2
RUN wget https://github.com/fwupd/fwupd/releases/download/2.0.19/fwupd-2.0.19.tar.xz
RUN tar xvf fwupd-2.0.19.tar.xz

WORKDIR fwupd-2.0.19

RUN python3 ./contrib/ci/fwupd_setup_helpers.py install-dependencies -y --os debian -y
ENV DEBEMAIL="your-email@example.com"
ENV DEBFULLNAME="Your Name"
ENV DEB_BUILD_OPTIONS=nostrip=no

RUN dh_make -s -n -f "../fwupd-2.0.19.tar.xz" -y

RUN printf "\n\noverride_dh_auto_configure:\n\tdh_auto_configure -- \
    -Dauto_features=enabled \
    -Dbluez=disabled \
    -Dcbor=disabled \
    -Ddocs=disabled \
    -Dintrospection=disabled \
    -Dlibarchive=disabled \
    -Dlibdrm=disabled \
    -Dlibmnl=disabled \
    -Dpassim=disabled \
    -Dplugin_flashrom=disabled \
    -Dplugin_modem_manager=disabled \
    -Dpolkit=disabled \
    -Dprotobuf=disabled \
    -Dsystemd=disabled \
    -Dtests=false \
    -Dumockdev_tests=disabled \
    -Dvalgrind=disabled \
    -Dvalgrind=disabled \
    -Dbash_completion=false \
    -Dblkid=disabled \
    -Dbuild=standalone \
    -Dfirmware-packager=false \
    -Dfish_completion=false \
    -Dgnutls=disabled \
    -Dhsi=disabled \
    -Dlvfs=disabled \
    -Dman=false \
    -Dqubes=false \
    -Dreadline=disabled \
    -Dplugin_uefi_capsule_splash=false \
    -Dvendor_ids_dir=/usr/share/misc" >> debian/rules

RUN printf "\noverride_dh_shlibdeps:\n\t-dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info\n" >> debian/rules

RUN debuild -b -j$(nproc) -us -uc
######################################################################
FROM debian:trixie-slim as firmware-installer

RUN apt-get update --no-install-recommends  \
    && apt-get install -y --no-install-recommends  \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    python3 \
    sudo \
    xz-utils \
    && rm -rf /var/lib/apt/lists/*

COPY --link --from=clang-builder hdctools-docker-fake_9999-1_all.deb /
RUN apt-get install -y /hdctools-docker-fake_9999-1_all.deb

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/cloud.google.gpg
RUN sudo apt-get update && sudo apt-get install -y google-cloud-cli

RUN mkdir -p /usr/share/servo_updater/firmware/
WORKDIR /usr/share/servo_updater/firmware/
COPY /dockerfiles/servo_firmware_provision.py servo_firmware_provision.py
RUN python3 servo_firmware_provision.py && rm servo_firmware_provision.py


######################################################################
FROM debian:trixie-slim as base

COPY --from=clang-builder hdctools-docker-fake_9999-1_all.deb /

COPY dockerfiles/requirements_base.txt /tmp/requirements_base.txt

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libcurl3t64-gnutls \
    libjcat1 \
    libpci3 \
    libxmlb2 \
    sudo \
    udev \
    usb.ids \
    iptables \
    lsof \
    procps \
    python3 \
    python3-backoff \
    python3-packaging \
    python3-pexpect \
    python3-pip \
    python3-mypy \
    pylint \
    python3-protobuf \
    python3-requests \
    python3-serial \
    python3-usb \
    usbutils \
    python3-grpc-tools \
    python3-grpcio \
    wget \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install --require-hashes --ignore-installed -r /tmp/requirements_base.txt --break-system-packages \
    && update-alternatives --set ip6tables /usr/sbin/ip6tables-nft \
    && apt-get install -y /hdctools-docker-fake_9999-1_all.deb \
    && rm -f /hdctools-docker-fake_9999-1_all.deb

# Install libusb.
COPY --link --from=libusb-builder /usr/local/include/libusb-1.0/libusb.h /usr/local/include/libusb-1.0/
COPY --link --from=libusb-builder /libusb/*.pc /usr/lib/pkgconfig/
COPY --link --from=libusb-builder /usr/local/lib/libusb-1.0.so.?.?.? /usr/local/lib/
COPY --from=libusb-builder /usr/local/lib/libusb-1.0.a /usr/local/lib

WORKDIR /wheels
COPY --link --from=pigweed-builder /pigweed/dist/*.whl ./
RUN pip3  install  *.whl --break-system-packages
WORKDIR /
RUN rm -rf wheels

# Install servo_firmware.
RUN mkdir -p /usr/share/servo_updater/firmware/

# Install servo_firmware.
RUN mkdir -p /usr/share/servo_updater/firmware/
COPY --link --from=firmware-installer /usr/share/servo_updater/firmware/ /usr/share/servo_updater/firmware/

COPY --link --from=chromiumos_overlays \
    /chromiumos-overlay/dev-embedded/libftdi/files/confs/*.conf \
    /usr/share/libftdi/

# Install genesys hub firmware
RUN mkdir -p /usr/local/genesys
RUN wget https://storage.googleapis.com/fwupd-cache/GenesysLogic_Google_Servo_GL3590_64.18.cab \
    -O /usr/local/genesys/GenesysLogic_Google_Servo_GL3590_64.18.cab
COPY --link --from=fwupd-builder /fwupd_*.deb .
RUN apt install -y ./fwupd_*.deb
RUN rm *.deb

# Install ec tools
COPY --link --from=ec-builder \
    /ec/extra/usb_updater/usb_updater2 \
    /ec/build/host/util/stm32mon \
    /ec/build/host/util/uartupdatetool \
    /ec/build/host/util/iteflash \
    /ec/build/host/util/itecomdbgr \
    /ec/build/host/util/rtkupdate \
    /ec/util/flash_ec \
    /ec/util/uart_stress_tester.py \
    /usr/sbin/

COPY --link --from=gcstool-builder \
    /ec/extra/usb_updater/gsctool \
    /usr/sbin/

RUN chmod u+x /usr/sbin/* /usr/bin/*

COPY --link --from=ec-builder libs.tar .
RUN tar xvf libs.tar
RUN rm libs.tar

RUN mkdir -p /usr/share/ec-devutils

COPY --link --from=ec-builder /ec/util/openocd/* /usr/share/ec-devutils/

# Microchip EC flash support
RUN mkdir -p /util/mchp
COPY --link --from=ec-builder /ec/util/mchp/crisis_rcvry_util.py /util/mchp

# Fetch NPCX monitor from GCS
RUN wget https://storage.googleapis.com/chromeos-localmirror/distfiles/cros_ec/npcx_monitor/npcx_monitor-2025.02.11.bin \
    -O /usr/share/ec-devutils/npcx_monitor.bin

# Fetch Realtek monitor from GCS
RUN wget https://storage.googleapis.com/chromeos-localmirror/distfiles/cros_ec/rtk_flame/rts5915_flash_upload-16687.0.0.bin \
    -O /usr/share/ec-devutils/rts5915_flash_upload.bin

RUN mkdir -p /usr/share/cros_ec/tokens
# Fetch EC Token Database from GCS
RUN wget https://storage.googleapis.com/chromeos-localmirror/distfiles/cros_ec/tokens/chromeos-ec-token-historical.bin \
    -O /usr/share/cros_ec/tokens/historical.bin

# Install flashrom
COPY --link --from=flashrom-builder /usr/local/sbin/flashrom /usr/local/sbin/
RUN chmod 755 /usr/local/sbin/flashrom

#Install futility
COPY --link --from=futility-builder /usr/bin/futility /usr/bin/
RUN chmod 755 /usr/bin/futility
COPY --from=futility-builder /usr/local/lib/*/libflashrom.so.1.0.0 /usr/lib
RUN ln -s /usr/lib/libflashrom.so.1.0.0 /usr/lib/libflashrom.so.1 && \
    ln -s /usr/lib/libflashrom.so.1.0.0 /usr/lib/libflashrom.so

RUN ln -s /usr/bin/futility /usr/bin/dump_fmap; \
    ln -s /usr/bin/futility /usr/bin/dump_kernel_config; \
    ln -s /usr/bin/futility /usr/bin/gbb_utility; \
    ln -s /usr/bin/futility /usr/bin/vbutil_kernel; \
    ln -s /usr/bin/futility /usr/bin/vbutil_key; \
    ln -s /usr/bin/futility /usr/bin/vbutil_keyblock

# Install cbfstool for flashrom and ec.
COPY --link --from=coreboot /coreboot/util/cbfstool/cbfstool /usr/local/bin/
RUN chmod 755 /usr/local/bin/cbfstool
COPY --link --from=coreboot /coreboot/util/ifdtool/ifdtool /usr/local/bin/
RUN chmod 755 /usr/local/bin/ifdtool

# Install shflags
COPY --link --from=shflags-builder shflags/shflags /usr/share/misc/shflags


COPY --link --from=chromiumos_overlays \
    /chromiumos-overlay/dev-embedded/libftdi/files/confs/*.conf \
    /usr/share/libftdi/

COPY --link --from=ec-builder libs.tar .
RUN tar xvf libs.tar
RUN rm libs.tar

ENV WARN_ONLY_ON_UNKNOWN_ENV="SERVO_FW_ALL_CHANNEL_OK"

COPY /dockerfiles/update_servo_firmware.py \
    /dockerfiles/start_servod.sh \
    /dockerfiles/start_servod_dev.sh \
    /dockerfiles/stop_servod.sh /

# Running sync in the container with no params will crash the host bare metal as all disks
# are mounted, put a script in the place of sync that checks are lease one argument is passed
# if no arguments are passed an error is thrown.
RUN mv /bin/sync /usr/local/bin/real_sync
COPY /dockerfiles/sync /bin
RUN chmod 755 /bin/sync

# Try to remove as much as possible to make the container smaller
RUN apt-get remove --purge -y \
    wget \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/cache/debconf \
    && rm -rf /usr/share/doc \
    && rm -rf /usr/share/zoneinfo/

RUN rm -rf /usr/share/doc/* /usr/share/man/* /usr/share/locale/*
RUN find /usr/share/locale -mindepth 1 -maxdepth 1 ! -name "en" -exec rm -rf {} +

# Copy versions files
COPY --link --from=coreboot /version.txt /version-coreboot.txt
COPY --link --from=ec-builder /version.txt /version-ec.txt
COPY --link --from=flashrom-builder /version.txt /version-flashrom.txt
COPY --link --from=futility-builder /version.txt /version-futility.txt
COPY --link --from=libusb-builder /version.txt /version-libusb.txt
COPY --link --from=pigweed-builder /version.txt /version-pigweed.txt
RUN bash -c "cat /version-*.txt | sort | uniq > /versions.txt && rm /version-*.txt"
