#!/usr/bin/env python3
# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import argparse
from datetime import datetime
import os
import sys

import docker


DEFAULT_IMAGE = "servod:dev"
ARTIFACT_URL_TEMPLATE = "us-docker.pkg.dev/chromeos-hw-tools/servod/servod:%s"


def setup():
    return docker.from_env()


def get_image(client, channel):
    if channel != "local":
        image = ARTIFACT_URL_TEMPLATE % channel
        client.images.pull(image)
        return image
    return DEFAULT_IMAGE


def start_servo_updater(
    client,
    image,
    file,
    passthrough_args,
):
    now = datetime.now()
    container_name = now.strftime("%s")

    name = "%s-docker_servo_updater" % container_name

    command = ["/usr/local/bin/servo_updater"] + passthrough_args

    volumes = ["/dev:/dev"]

    _servodrc = os.path.join(os.path.expanduser("~"), ".servodrc")
    if os.path.isfile(_servodrc):
        volumes.append(f"{_servodrc}:/root/.servodrc:ro")

    if file:
        dir_path = os.path.dirname(file)
        new_file_path = f"/tmp/{os.path.basename(file)}"

        # mount directory from host containing FW binary to container
        volumes.append(f"{dir_path}:/tmp/")

        for i, arg in enumerate(passthrough_args):
            if file in passthrough_args:
                passthrough_args[i] = new_file_path

        # pass arg to servo_updater command with valid path from container side
        command += ["-f", new_file_path]

    cont = client.containers.run(
        image,
        privileged=True,
        stderr=True,
        tty=True,
        name=name,
        hostname=name,
        detach=True,
        volumes=volumes,
        entrypoint=command,
    )
    output = cont.attach(stdout=True, stderr=True, stream=True, logs=True)
    for line in output:
        print(line.decode("utf-8"), end="")
    result = cont.wait()
    ec = result["StatusCode"]
    cont.remove()
    return ec


def parse_args():
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument(
        "--updater_channel",
        type=str,
        choices=["local", "latest", "beta", "release"],
        default="release",
        help="Select docker image to use.",
    )
    parser.add_argument(
        "-f",
        "--file",
        type=str,
        help="Update servo with specific file.",
    )
    return parser.parse_known_args()


def main():
    client = setup()
    args, passthrough_args = parse_args()
    print("Getting docker image...")
    image = get_image(client, args.updater_channel)
    print("Starting docker container...")
    ec = start_servo_updater(
        client=client,
        image=image,
        file=args.file,
        passthrough_args=passthrough_args,
    )
    sys.exit(ec)


if __name__ == "__main__":
    main()
